### ISSUE TITLE
Backwards compatibility with hg19

### ISSUE THREAD

**Issue by ARChakravarthy** [andrewrech/antigen.garnish#139]
I notice the metadata files you have in the extdata folder are to do with GRCh38 ; is the package compatible with hg19 variant calls, or is the use of liftOver recommended? It would be helpful if the documentation clarified this.

**Comment by andrewrech** [comment]
Thank you @ARChakravarthy for your interest in the software. I clarified in the README that GRCh38 is required.

Yes, you will need to use liftOver. A specific GRCh38 transcript version number is required to make sure the peptides are registered correctly.
