### ISSUE TITLE
Error: unset environmental variable for antigen.garnish data directory

### ISSUE THREAD

**Issue by ARChakravarthy** [andrewrech/antigen.garnish#140]
I've been running tests of the latest version on R 4.1.0 using the inbuilt examples. 

library(magrittr)
library(data.table)
library(antigen.garnish)

# load an example VCF
dir <- system.file(package = "antigen.garnish") %>%
       file.path(., "extdata/testdata")

file <- file.path(dir, "TUMOR.vcf")

# extract variants
dt <-  garnish_variants(file)

# add space separated MHC types
# see list_mhc() for nomenclature of supported alleles
# MHC may also be set to "all_human" or "all_mouse" to use all supported alleles

dt[, MHC := c("HLA-A*01:47 HLA-A*02:01 HLA-DRB1*14:67")]

# predict neoantigens
result <- dt %>% garnish_affinity(.)

#Console output when function breaks

Generating metadata.
Reading local transcript metadata.
Environmental variable AG_DATA_DIR for the antigen.garnish data directory is unset. Checking standard directories.
Error in Sys.setenv(AG_DATA_DIR = ag_dir) : object 'ag_dir' not found
Removing temporary files.

**Comment by andrewrech** [comment]
Thanks for your message. I'm happy to help you get this working.

It appears that the external (to R) dependencies are not installed correctly. Could you provide a reproducible example of how you installed the package and additional information about your system and R environment?

I recommend using the Docker image we provide if possible, which will avoid these issues. Are you able to try Docker?

**Comment by ARChakravarthy** [comment]
Thank you for your help, appreciate it greatly! 

The installation is being handled by IT support on an institutional HPC so I am afraid I don't have access to the installation scripts they are using directly.

If you point me to a relative path tree for the folder structure of the external dependencies I think it would be most illuminating.

**Comment by andrewrech** [comment]
Hi,

This error message indicates that the installation instructions haven't been followed correctly, so I'm afraid I can't point you to the where these files have been installed.

Thanks

**Comment by ARChakravarthy** [comment]
I have asked IT for a copy of the installation script they used, I will update you once I have it.

**Comment by ARChakravarthy** [comment]
Turns out they messed up the installation of the dependencies. Closing the issue.
