### ISSUE TITLE
garnish_antigens filtering

### ISSUE THREAD

**Issue by nickhir** [andrewrech/antigen.garnish#144]
I have a few questions regarding the `garnish_antigens` filtering.
The documentation says, that the tool returns a data frame with ranked neoepitopes. 
I was wondering if you could elaborate how exactly the ranking is done, e.g. if certain criteria's are weighted more than others. 
Furthermore, I was wondering why some antigens in my case passed the filtering. Here is a subset of them:
![image](https://user-images.githubusercontent.com/49643134/139081068-55200e6e-8a1e-4c67-93c4-940913110cb3.png)

The last one for example has a foreigness_score of 0, so I though it should be removed (default parameter is `foreignness_threshold = 1e-15`). 
The `min_DAI` column also confuses me, because I though the value should be at least 10. Is for the filtering the mean_DAI considered?

Thank you in advance!

**Comment by leeprichman** [comment]
Hi Nickhir!

Sorry this is unclear, it also appears the function wasn't passing the arguments correctly. This function returns any mutant peptide with binding affinity ("Ensemble_score") < the affinity threshold (default 34). Then the other properties (dissimilarity, IEDB, and DAI) are used to label peptides in the "Recognition_Features" column but do not drop them from the table. So the only filtering that occurs is based on binding affinity < affinity_threshold.

Andrew is going to update the documentation to make it clearer and make sure the threshold arguments are passed correctly.

**Comment by andrewrech** [comment]
https://github.com/andrewrech/antigen.garnish/commit/551e332b519fa8cd6945f112bfec44bdd0de8019
