### ISSUE TITLE
No outputs for some queries when estimating foreignness scores

### ISSUE THREAD

**Issue by ARChakravarthy** [andrewrech/antigen.garnish#146]
Using antigen garnish 2.3  running on Linux, R 4.0.4, I have found that out of a query containing 287000 peptides, only about 61k returned a foreignness score, and each of the results that were actually returned included a peptide in the IEDB_anno column as well. 

Under what circumstances does this function not return an output? 
Does the IEDB annotation in the results represent the closest hit in the IEDB, or an exact match? 

I have attached a screenshot with some of the peptide sequences that do not return a match. 

Dissimilarity scores are returned for a much larger fraction of the query , for context. 

![IEDB_Results](https://user-images.githubusercontent.com/7645147/151417405-dbca79fe-9af5-4f26-a2ab-2d7886bc6bbd.jpg)

**Comment by leeprichman** [comment]
The is only a foreignness score returned when BLAST against the IEDB-derived db is returned for a given peptide. A value of NA means there were no alignments, which one could interpret as the same as a foreignness score of 0, but we leave that to up to the user to decide.

The IEDB_anno column is the single BLAST result with the highest alignment score to the peptide.

**Comment by ARChakravarthy** [comment]
Thank you, that clarifies it.
