### ISSUE TITLE
Using own vcf file in docker

### ISSUE THREAD

**Issue by antaralabiba97** [andrewrech/antigen.garnish#147]
Hi,

I have successfully run the README file using the docker system instructions. I am now trying to use your pipeline on my own variant files. I am new to using docker but have read around the commands and using the instructions on your README file I copied my file using the following:

docker cp /Users/antaralabiba/Downloads/variants.vcf $cID:/variants.vcf

However, once I execute and enter the container defined I am unable to find my vcf file? An error does not come up when copying my file into docker so I am sure it is being copied correctly, as copying the netmhc files from my local computer into the container and running the installation script was successful.

When I enter the docker container there are two directories: antigen.garnish and src. Not sure where to look for my variants.vcf file as I checked and it is not in any of the directories. 

Any help is appreciated as I am really hopeful about the pipelines use in my research!

Thank you.

**Comment by andrewrech** [comment]
Hi, thanks for trying the software. I'm not sure, but this could be a simple issue. The path on the ride side is from the docker container root:

`docker cp /Users/antaralabiba/Downloads/variants.vcf $cID:/variants.vcf`

So inside the container the variant file would be located at `/`.

If you wanted to put it in `src`, you would run:

`docker cp /Users/antaralabiba/Downloads/variants.vcf $cID:/root/src`
