### ISSUE TITLE
garnish_affinity process killed when running all human alleles 

### ISSUE THREAD

**Issue by antaralabiba97** [andrewrech/antigen.garnish#149]
Hi,

I have run antigen garnish on my own vcf file using the three HLA alleles listed on the README and wanted the next step to be running against all the human HLA alleles available in the package. I first thought to run the garnish_affinity function using all the HLA human alleles available on the test data but the process is killed. I am running it on the new Mac M1 Pro and have increased the docker memory to 16GB and disk image size to 248GB. 

Any help on how to overcome this would be appreciated! Thank you. 

![Screenshot 2022-05-31 at 15 00 28](https://user-images.githubusercontent.com/80478944/171193027-06d7fdb7-2f8a-4592-9f81-a9227fc82b24.png)

**Comment by andrewrech** [comment]
Thanks for trying the software. I am happy to try to help.

My first guess is that you are running out of memory. Can you take a look at the container memory usage while the process is running (for instance with something like [lazydocker](https://github.com/jesseduffield/lazydocker))? That is a lot for HLA alleles - it is possible that, in your case, 2Gb per core is not enough memory to send the table to each forked process. Try giving the docker container 2 cores only.

My second guess is that this is some issue related to cross-arch virtualization under Docker, but this is less likely if the README example is working.

**Comment by andrewrech** [comment]
Oh, also, since you are running this on a laptop, you may want to consider running only the 50 or 100 or 200 most common HLA alleles. I am not sure of your experimental question, but running every possible allele will take a long time.

**Comment by antaralabiba97** [comment]
Hi, sure makes sense. Will try the above with the test data and my data and if all is working I will close the issue. Also thank you for your prompt response!
