### ISSUE TITLE
no score calculated

### ISSUE THREAD

**Issue by dxl3742** [andrewrech/antigen.garnish#154]
Hey Andrew,
When I loaded the package, it reported "Skipping BLAST because ncbiblast+ is not in PATH", I downloaded blast, now it runs but doesn't give me any scores.

> v %>% foreignness_score(db = "human") %>% print
Generating FASTA to query.
Running blastp for homology to IEDB antigens.
Removing temporary fasta files.
        nmer
1:  SIINFEKL
2: ILAKFLHWL
3: GILGFVFTL
> v %>% dissimilarity_score(db = "human") %>% print
Running blastp for homology to self antigens.
Removing temporary fasta files.
        nmer
1:  SIINFEKL
2: ILAKFLHWL
3: GILGFVFTL

It would be great if you could help, thanks in advance!

**Comment by dxl3742** [comment]
I'm thinking I have to download the database as well? I remember the first time I ran it downloaded loads of stuff and was working at some point, then I don't know what changed to get the warning. I can still find the original ncbi folder under /antigen.garnish, except there aren't any executables inside.

**Comment by dxl3742** [comment]
Hi, I deleted the previous installation and reinstalled the package, now I am still getting the "Skipping BLAST because ncbiblast+ is not in PATH" error.

**Comment by dxl3742** [comment]
https://github.com/andrewrech/antigen.garnish/issues/138
Didn't set the AG_DATA_DIR and path for blast (why is this not mentioned in the installation guide?) closing now.

**Comment by guanghua13** [comment]
Hi,
    When I loaded the package, it was also reported "Skipping BLAST because ncbiblast+ is not in PATH".May I ask what's going on?
