### ISSUE TITLE
Foreignness for mouse data

### ISSUE THREAD

**Issue by saraahwallace** [andrewrech/antigen.garnish#155]
Hi, 

Just wanted to check before I got too in depth into the download for this, does the foreignness calculation have compatibility with mice?

**Comment by leeprichman** [comment]
Hi Saraah,

Yes, foriegnness calculation can be performed for mouse, and it is automatically detected based on the HLA type input (if "H-2" is detected the species is set to mouse. That said, foreignness for mice is adapted from the method in PMID: 29132144 using mouse data deposited in the IEDB. Their study was only using human data however, so mouse foreignness calculation is untested for its biological relevance.

**Comment by saharlccSCSU** [comment]
Hi,
We are trying to run antigen garnish on a GATK generated vcf.  We get the error below when calling garnish_variants(file). Any insights?

All variants processed
Error in stri_replace_all_regex(string, pattern, fix_replacement(replacement),  : 
  Illegal argument. (U_ILLEGAL_ARGUMENT_ERROR)
Calls: garnish_variants ... <Anonymous> -> <Anonymous> -> stri_replace_all_regex
Execution halted
