### ISSUE TITLE
Antigen.garnish missing columns in output file with fusion peptides

### ISSUE THREAD

**Issue by GHosking-01** [andrewrech/antigen.garnish#156]
Hi,
I am attempting to use antigen garnish to predict neoantigens from fusion proteins predicted by arriba/starfusion/fusioncatcher.
I took the predicted peptides from those programs (quite long, minimum of 60 amino acids) and ran them through the Docker version of fusioncatcher (I ran the example data to check everything was working and it was fine). I used fread in R to put my CSV file into a data.table and then used result <- garnish_affinity(mytable). 
An example of the format of my csv file
![image](https://github.com/andrewrech/antigen.garnish/assets/142370564/dcdb1690-d92c-4172-92cd-6ef52e33aa71)
MHC is for a balb-c mouse and used all for mutant index since they are novel fusion proteins.

I'm missing the columns: 

%Rank_EL_netMHCpan
command_netMHCpan
core_netMHCpan
Gl_netMHCpan
Gp_netMHCpan
icore_netMHCpan
Identity_netMHCpan
Il_netMHCpan
Ip_netMHCpan
Of_netMHCpan
pep_wt 
pos_netMHCpan
Score_EL_netMHCpan

and the columns  netMHCpan, netMHCII, netMHCIIpan, pos_netMHC and dai_uuid are empty in the output file.
Didn't see any errors in the readout for antigen garnish so I am unsure what is going wrong. Any help would be appreciated! Thanks.

**Comment by andrewrech** [comment]
> MHC is for a balb-c mouse 

Not sure the above tools have an option for this MHC. Could you check and also attach minimal input/output so I can repro? Thx

**Comment by GHosking-01** [comment]
See attached minimal input/output. Thanks! (docker output zipped- file was too large to upload directly)
[myagdockeroutput.zip](https://github.com/andrewrech/antigen.garnish/files/12851959/myagdockeroutput.zip)
[only1.csv](https://github.com/andrewrech/antigen.garnish/files/12851962/only1.csv)

**Comment by andrewrech** [comment]
Did you check that these tools have this MHC optional available? If not, output will be blank

**Comment by GHosking-01** [comment]
Sorry for the delayed reply- all of the tools support the mouse MHC for Balb-c according to their documentation.

***EDIT 21/11/23 
see output from antigen garnish
MHC netMHCpan netMHC netMHCII netMHCIIpan
![image](https://github.com/andrewrech/antigen.garnish/assets/142370564/5d97c19d-116d-4e25-a352-179225b109e9)
in that original input i did not specify MHCII alleles thus netMHCII, netMHCIIpan being empty. 
Since netMHCpan supports H2 alleles I am unsure of why antigen garnish won't process them
![image](https://github.com/andrewrech/antigen.garnish/assets/142370564/645a4503-186b-4ad2-a52c-03d8eb8e288e)

Thankyou!
