### ISSUE TITLE
detailed install instructions

### ISSUE THREAD

**Issue by davidballi** [andrewrech/antigen.garnish#26]
Add detailed install instructions to README.md that explain the installation of all necessary dependencies on a raw Ubuntu AWS AMI.

**Comment by leeprichman** [comment]
ami-88deeff3 latest bioconductor instance also an option to put in the readme?  just requires installing devtools and then can install the package right from there.

**Comment by andrewrech** [comment]
@leeprichman great idea

**Comment by andrewrech** [comment]
confirmed today that this works with current package. Need

`sudo apt get install subversion`

also would be good to upgrade:

`sudo apt get upgrade -y`

and from R

```r
source("https://bioconductor.org/biocLite.R")
biocLite()
install.packages("devtools")
```

**Comment by davidballi** [comment]
I have instructions for install on raw Ubuntu AMI [here](https://github.com/davidballi/antigen.garnish/blob/master/README.md).  submit pull request?

**Comment by andrewrech** [comment]
great, yes

**Comment by andrewrech** [comment]
#30
