### ISSUE TITLE
How does SnpEff handle rare insertions / deletions?

### ISSUE THREAD

**Issue by andrewrech** [andrewrech/antigen.garnish#3]
Do edge cases exist where SnpEff annotates [rare](http://varnomen.hgvs.org/recommendations/DNA/variant/deletion/) insertions / deletions as protein coding with nomenclature that will generate spurious peptides in `antigen.garnish::get_cDNA`?

These cases 

* `c.183_186+48del`
* `c.1149del`
* `1149+1del`
* `c.4072-1234_5155-246del`
* `c.19_21=/del`

are handled properly by the `_` lookahead/lookbehind:

```r
    dt[, cDNA_locs := cDNA_change %>%
          stringr::str_extract("[0-9]+") %>%
          as.integer]
    dt[, cDNA_locl := cDNA_change %>%
          stringr::str_extract("(?<=_)[0-9]+") %>%
          as.integer]
```

However, these cases 

* `c.(4071+1_4072-1)_(5154+1_5155-1)del`
* `c.(?_-245)_(31+1_32-1)del`
* `c.(?_-1)_(*1_?)del`

will be filtered out, but they should be extremely rare (would SnpEff annotate as structural variants?), and it is not clear what, if any, protein would be generated.

[test for this](https://github.com/andrewrech/antigen.garnish/blob/6d94d79b0bf053c3b02e8f444696394ab6dff85a/tests/manual/test-cDNA_edge_cases.R#L10)

**Comment by davidballi** [comment]
Wouldn't most of these be annotated as 'intron_variants'?

Also, how are cases of both a DEL and INS substitution be handled?   e.g.
`
c.2632_2633delGGinsAC
`
definite edge-cases that I have seen.

**Comment by andrewrech** [comment]
1 .Delins are handled by [deleting]() and then inserting on the deleted cDNA, so we catch these.
2. I think you are right, [SnpEff docs](http://snpeff.sourceforge.net/) suggest variants spanning an intronic region would not be [selected](https://github.com/andrewrech/antigen.garnish/blob/baccf4bfc409f53ddf578329417501d06286ea90/R/antigen.garnish.R#L721) for peptide generation.
3. I added a [filter](https://github.com/andrewrech/antigen.garnish/blob/baccf4bfc409f53ddf578329417501d06286ea90/R/antigen.garnish.R#L584) for cDNAs that don't conform to what we can interpret since stringr::* returns `NA` with no match.

I will leave this open pending running some large VCFs through.

baccf4bfc409f53ddf578329417501d06286ea90

**Comment by andrewrech** [comment]
Will test on large human dataset containing insertions and deletions

**Comment by andrewrech** [comment]
I think we have tested every variety of SnpEff annotation successfully. @davidballi
