### ISSUE TITLE
Accept xlsx input in garnish predictions

### ISSUE THREAD

**Issue by andrewrech** [andrewrech/antigen.garnish#31]
It would be helpful to accept `xlsx` input in `garnish_predictions` so users do not need to construct a data table.

- [ ] Provide example `xlsx` files
- [ ]  Allow garnish_predictions to take a path name from getwd() using `rio::import` and coerce to a data table. This would allow many input formats. Check class and proceed.

@davidballi @leeprichman thoughts?

**Comment by leeprichman** [comment]
Don't see why not, would certainly make it more accessible. Just add functionality to check if input is a filename or dt, then format of input, .xlsx or .csv/txt.  Only concern is that table might have names that contain special characters etc but check.names = TRUE should fix that right up.  We would never operate on those columns directly but its possible it would mess up something like merge().

**Comment by andrewrech** [comment]
Yea, and `rio::import` handles these import issues

**Comment by andrewrech** [comment]
#34
