### ISSUE TITLE
Question about interpreting results

### ISSUE THREAD

**Issue by mrForce** [andrewrech/antigen.garnish#35]
When run the "Predict neoepitopes" example, I get this:

> Meta line 56 read in.
> All meta lines processed.
> Character matrix gt created.
> Character matrix gt rows: 3
> Character matrix gt cols: 11
> skip: 0
> nrows: 3
> row_num: 0
> 
> Processed variant: 3
> All variants processed
>           sample_id priority_neos classic_neos classic_top_score alt_neos
> 1: normal_tumor.bam             0            0        0.01066477        5
>    alt_top_score mhc_binders variants transcripts predictions nmers
> 1:      35.80603          13        3           3         276   276
> 

I've seen the documentation for garnish_summary, but I'm still not sure how to interpret these results.

**Comment by andrewrech** [comment]
Hi @mrForce,

Thanks for your comment and trying out the package. I added some information to the [documentation](http://get.rech.io/antigen.garnish.pdf) for this function. Let me know if that is helpful, and what other information you would like.

Andrew

d1baef597ef83ecf03b9e1b815e47c250fa46a5f
