### ISSUE TITLE
garnish_summary returns null

### ISSUE THREAD

**Issue by leeprichman** [andrewrech/antigen.garnish#36]
When passing from garnish_jaffa > garnish_predictions > garnish_summary, null data.table is returned.

Does this happen for any time input to garnish_predictions is not from a VCF passed to garnish_variants?  ie when cDNA or peptide direct input is passed to garnish_predictions and no DAI is calculated.

**Comment by andrewrech** [comment]
84d9f7415a05f211630fcd0dba4c30c5de43cf48
