### ISSUE TITLE
Write examples

### ISSUE THREAD

**Issue by andrewrech** [andrewrech/antigen.garnish#4]
- [x] `garnish_predictions` non-VCF entry
- [x] `garnish_predictions` output column interpretation
- [x] `garnish_summary` output column interpretation
- [x] document column output https://github.com/andrewrech/antigen.garnish/commit/982af16360d79b9d08b63ab975dc5b4b1ee78993

**Comment by davidballi** [comment]
perhaps a `write_cDNA` for saving frameshift transcripts to disc?

**Comment by andrewrech** [comment]
Full wt and mut cDNA and peptides are in the output from `garnish_variants` - should definitely be documented. Added to above.
