### ISSUE TITLE
JAFFA gene names != mgi_symbol from biomaRt

### ISSUE THREAD

**Issue by andrewrech** [andrewrech/antigen.garnish#65]
Gene names returned from Jaffa are a superset of `mgi_symbol` gene names returned from biomaRt

**Comment by leeprichman** [comment]
#69 
resolved by explicitly using hgnc and mgi symbol with garnish_jaffa

**Comment by leeprichman** [comment]
#69 
resolved by explicitly using hgnc and mgi symbol with garnish_jaffa
