### ISSUE TITLE
note on required R version

### ISSUE THREAD

**Issue by davidballi** [andrewrech/antigen.garnish#7]
Add dependency on R version requirements:

`ERROR: this R is version 3.3.1, package 'antigen.garnish' requires R >=  3.4.1`

edit: missed this info in DESCRIPTION file.  Maybe add a line at top of README.md?

**Comment by andrewrech** [comment]
No reason to have this dep, I will revert to >= `3.2.5`

**Comment by andrewrech** [comment]
We need to match the latest Bioconductor release, so I pegged to that, `3.4`
