### ISSUE TITLE
List licensing requirements of dependencies in README

### ISSUE THREAD

**Issue by andrewrech** [andrewrech/antigen.garnish#79]

**Comment by davidballi** [comment]
Another option would be to add a download flag to the installation script that specifies which tools to download and install:

`$ curl -fsSL http://get.rech.io/antigen.garnish.sh`
`$ sudo sh antigen.garnish.sh --download All` 
or 
`$ sudo sh antigen.garnish.sh --download MHCflurry, MHCnuggets, netMHCII` 

Thoughts?

**Comment by andrewrech** [comment]
Yea, I like this idea. Some code modification is needed to bypass non-installed tools, which should be trivial.

**Comment by andrewrech** [comment]
In wiki
