### ISSUE TITLE
add detailed svg to wiki

### ISSUE THREAD

**Issue by andrewrech** [andrewrech/antigen.garnish#90]
@leeprichman

**Comment by andrewrech** [comment]
[need svg and code](https://github.com/andrewrech/antigen.garnish/wiki/Package-schematic)

**Comment by leeprichman** [comment]
done, @andrewrech let me know when you rebuild and S3 is updated with new svg and I will change the link in the wiki to the svg from png

**Comment by andrewrech** [comment]
15880a7
